#Name - **Omkar Shinde**

PRN - **202201040190**

Roll No - **582**

Div - **E4**






# Introduction to **NumPy** and **Matrices**
## Why use **NumPy**?


In [ ]:
## Installing **NumPy**
!pip install numpy

In [ ]:
##Importing NumPy
import numpy as np

#Creating NumPy Arrays
Using the numpy.array() function:

In [4]:
import numpy as np

Pro_list = [1, 2, 3, 4, 5]
Pro_array = np.array(Pro_list)


In [5]:
import numpy as np

Matrix = np.array([[1, 2, 3], [4, 5, 6]])

print(Matrix)



[[1 2 3]
 [4 5 6]]


# **Matrix** Addition
Matrix addition involves adding corresponding elements of two matrices. NumPy provides the` np.add()` function to perform matrix addition efficiently. Here's an example:

In [6]:
import numpy as np
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

result = np.add(matrix1, matrix2)

print(result)


[[10 10 10]
 [10 10 10]
 [10 10 10]]


# **Matrix** Subtraction
Similar to addition, matrix subtraction involves subtracting corresponding elements of two matrices. NumPy provides the` np.subtract()` function for matrix subtraction. Here's an example:

In [7]:
import numpy as np

# Matrix subtraction using NumPy
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

result = np.subtract(matrix1, matrix2)

print(result)


[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


# **Matrix** Multiplication
Matrix multiplication is a fundamental operation in linear algebra. NumPy provides the `np.dot()` function for matrix multiplication. Here's an example

In [8]:
import numpy as np

# Matrix multiplication using NumPy
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

result = np.dot(matrix1, matrix2)

print(result)


[[ 58  64]
 [139 154]]


# **Matrix** Transposition
Matrix transposition involves interchanging the rows and columns of a matrix. NumPy provides the `np.transpose()` function for matrix transposition. Here's an example:

In [9]:
import numpy as np

# Matrix transposition using NumPy
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

result = np.transpose(matrix)

print(result)


[[1 4]
 [2 5]
 [3 6]]
